### ISSUE TITLE
Pattern support

### ISSUE THREAD

**Issue by dgitis** [websevendev/attributes-for-blocks#5]
Currently, when attributes-for-blocks is set on a Wordpress Pattern block, the attributes only appear on the instance of the block in which it was set.

I believe it would be better if the attributes appeared on all instances of a pattern.

It seems like the way to do this would be to use the `render_block_data` [hook](https://developer.wordpress.org/reference/hooks/render_block_data/) instead of the `render_block` hook.

**Comment by websevendev** [comment]
![image](https://github.com/websevendev/attributes-for-blocks/assets/18283192/d54a0a9a-ae7e-41b9-8d51-ea5a7b60b55e)

Are you changing the attributes on the actual pattern block (called "test" on the image above)? Then yes, it only applies to that particular instance.

If you want to change attributes that sync for all instances of the pattern (assuming it's a "synced" pattern), you'll have to edit the attributes on the block that is inside the pattern ("Paragraph" on the picture). The pattern block itself is not part of the pattern, it only "contains" it.

It looks like in WP 6.5 you can't even edit attributes on the pattern block itself anymore: https://playground.wordpress.net/?plugin=attributes-for-blocks&url=%2Fwp-admin%2Fpost.php%3Fpost%3D2%26action%3Dedit&wp=beta

**Comment by dgitis** [comment]
Interesting, I thought I edited an internal block first but editing internal blocks now clearly saves the pattern wherever I do it. Sorry for wasting your time and thanks for your help.
